default_language_version:
  python: python3.11
repos:
  # Pre-commit maintained utility hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer
        types: [text]
      - id: trailing-whitespace
        types: [text]
      - id: mixed-line-ending
        types: [text]
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast

  # Darglint docstring checker
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint

  # Ruff linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        require_serial: true

  # Black formatter
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        require_serial: true
